services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./DY_PMS_dump.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  setup-mysql:
    image: mysql:8.0
    container_name: setup-mysql
    depends_on:
      - mysql
    entrypoint: >
      sh -c "
      echo 'Waiting for MySQL to be ready...';
      until mysqladmin ping -h mysql -p${MYSQL_ROOT_PASSWORD} --silent; do
        sleep 1
      done;
      echo 'MySQL is ready, executing setup script...';
      MYSQL_PWD=\"${MYSQL_ROOT_PASSWORD}\" mysql -h mysql -u root -e \"
      ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '${MYSQL_ROOT_PASSWORD}';
      FLUSH PRIVILEGES;\"
      exit 0;
      "
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
  
  nestjs-app:
    image: node:20
    container_name: nestjs-app
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "yarn install && yarn run start:dev"
    environment:
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_NAME: ${DATABASE_NAME}
    ports:
      - "3000:3000"  
    depends_on:
      - mysql
      - setup-mysql


volumes:
  mysql_data:
    driver: local