version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./PMS_dump.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  # nestjs:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nestjs
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_PORT: 3306
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mysql
  #   restart: always

volumes:
  mysql_data:
    driver: local